services:
  - type: web
    name: solar-forecast-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && PYTHONPATH=. alembic upgrade head && PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: VISUAL_CROSSING_API_KEY
        sync: false
      - key: PVOUTPUT_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false


