"""Add weather_source to generation_forecasts

Revision ID: 015c85e19da5
Revises: d60127907a7d
Create Date: 2026-08-13 14:10:57.847147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015c85e19da5'
down_revision: Union[str, Sequence[str], None] = 'd60127907a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_forecasts', sa.Column('weather_source', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('uq_station_generation_timestamp'), 'generation_forecasts', type_='unique')
    op.create_unique_constraint('uq_station_weather_model_timestamp', 'generation_forecasts', ['station_id', 'weather_source', 'model_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_station_weather_model_timestamp', 'generation_forecasts', type_='unique')
    op.create_unique_constraint(op.f('uq_station_generation_timestamp'), 'generation_forecasts', ['station_id', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.drop_column('generation_forecasts', 'weather_source')
    # ### end Alembic commands ###
