"""Add generation forecasts table

Revision ID: 04fa96ae97cd
Revises: 10f9a227fe61
Create Date: 2026-08-12 17:38:28.841534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fa96ae97cd'
down_revision: Union[str, Sequence[str], None] = '10f9a227fe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_power_kw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['neural_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'timestamp', name='uq_station_generation_timestamp')
    )
    op.create_index(op.f('ix_generation_forecasts_id'), 'generation_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_generation_forecasts_model_id'), 'generation_forecasts', ['model_id'], unique=False)
    op.create_index(op.f('ix_generation_forecasts_station_id'), 'generation_forecasts', ['station_id'], unique=False)
    op.create_index(op.f('ix_generation_forecasts_timestamp'), 'generation_forecasts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_forecasts_timestamp'), table_name='generation_forecasts')
    op.drop_index(op.f('ix_generation_forecasts_station_id'), table_name='generation_forecasts')
    op.drop_index(op.f('ix_generation_forecasts_model_id'), table_name='generation_forecasts')
    op.drop_index(op.f('ix_generation_forecasts_id'), table_name='generation_forecasts')
    op.drop_table('generation_forecasts')
    # ### end Alembic commands ###
