"""Add neural models table

Revision ID: 10f9a227fe61
Revises: 5963f4a7ada7
Create Date: 2026-08-12 16:57:54.523304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f9a227fe61'
down_revision: Union[str, Sequence[str], None] = '5963f4a7ada7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neural_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neural_models_id'), 'neural_models', ['id'], unique=False)
    op.create_index(op.f('ix_neural_models_station_id'), 'neural_models', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neural_models_station_id'), table_name='neural_models')
    op.drop_index(op.f('ix_neural_models_id'), table_name='neural_models')
    op.drop_table('neural_models')
    # ### end Alembic commands ###
