"""Add solar astronomical fields to weather_forecasts

Revision ID: 1a01c4a4e8bf
Revises: 5253e4160926
Create Date: 2026-08-13 13:23:37.909909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a01c4a4e8bf'
down_revision: Union[str, Sequence[str], None] = '5253e4160926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('st_s', sa.Integer(), nullable=False))
    op.add_column('weather_forecasts', sa.Column('h_svetl', sa.Float(), nullable=False))
    op.add_column('weather_forecasts', sa.Column('azimuth', sa.Float(), nullable=False))
    op.add_column('weather_forecasts', sa.Column('elevation', sa.Float(), nullable=False))
    op.add_column('weather_forecasts', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('weather_forecasts', sa.Column('ww', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecasts', 'ww')
    op.drop_column('weather_forecasts', 'day_of_week')
    op.drop_column('weather_forecasts', 'elevation')
    op.drop_column('weather_forecasts', 'azimuth')
    op.drop_column('weather_forecasts', 'h_svetl')
    op.drop_column('weather_forecasts', 'st_s')
    # ### end Alembic commands ###
