"""Add code column to neural_models

Revision ID: 2a41e5cd6405
Revises: 015c85e19da5
Create Date: 2026-08-13 14:36:05.434113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a41e5cd6405'
down_revision: Union[str, Sequence[str], None] = '015c85e19da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('neural_models', sa.Column('code', sa.String(length=50), nullable=False, server_default='baseline'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neural_models', 'code')
    # ### end Alembic commands ###
