"""Add source to uq_station_source_weather_timestamp

Revision ID: 471578336f12
Revises: 2a41e5cd6405
Create Date: 2026-08-13 14:42:24.739791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471578336f12'
down_revision: Union[str, Sequence[str], None] = '2a41e5cd6405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_station_weather_timestamp'), 'weather_forecasts', type_='unique')
    op.create_unique_constraint('uq_station_source_weather_timestamp', 'weather_forecasts', ['station_id', 'source', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_station_source_weather_timestamp', 'weather_forecasts', type_='unique')
    op.create_unique_constraint(op.f('uq_station_weather_timestamp'), 'weather_forecasts', ['station_id', 'timestamp'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
