"""Add source column to weather_forecasts

Revision ID: 5253e4160926
Revises: 04fa96ae97cd
Create Date: 2026-08-12 19:38:59.108984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5253e4160926'
down_revision: Union[str, Sequence[str], None] = '04fa96ae97cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('source', sa.String(length=50), server_default='Open-Meteo', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecasts', 'source')
    # ### end Alembic commands ###
