"""Add weather forecasts table

Revision ID: 5963f4a7ada7
Revises: cc3332ac89ef
Create Date: 2026-08-12 16:08:38.244189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5963f4a7ada7'
down_revision: Union[str, Sequence[str], None] = 'cc3332ac89ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'timestamp', name='uq_station_weather_timestamp')
    )
    op.create_index(op.f('ix_weather_forecasts_id'), 'weather_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_station_id'), 'weather_forecasts', ['station_id'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_timestamp'), 'weather_forecasts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_forecasts_timestamp'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_station_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_id'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    # ### end Alembic commands ###
