"""Add predicted_power_watts to generation_forecasts

Revision ID: d60127907a7d
Revises: 1a01c4a4e8bf
Create Date: 2026-08-13 13:40:23.532960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60127907a7d'
down_revision: Union[str, Sequence[str], None] = '1a01c4a4e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_forecasts', sa.Column('predicted_power_watts', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_forecasts', 'predicted_power_watts')
    # ### end Alembic commands ###
